[env:waveshare-s3-lcd-185]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; --- Match Waveshare's hardware ---
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

; it tells the build system "flash is QIO, PSRAM is OPI (octal)." If you get this wrong, 
; PSRAM won't initialize and your framebuffer allocation will fail silently. This is the 
; single most common mistake with this board in PlatformIO.
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1


; For now we skip lvgl as UI library, i want to push my own bytes for fun...
lib_deps =
    moononournation/GFX Library for Arduino@^1.4.9
    Wire